/*
 * Copyright 2026 Amazon.com, Inc. or its affiliates.
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.amazonaws.services.schemaregistry.integrationtests.kafkaconnect.protobuf

import com.amazonaws.services.schemaregistry.integrationtests.properties.GlueSchemaRegistryConnectionProperties
import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.ProtobufSchemaConverter
import com.amazonaws.services.schemaregistry.utils.AWSSchemaRegistryConstants
import org.apache.kafka.connect.data.Schema
import org.apache.kafka.connect.data.SchemaBuilder
import org.apache.kafka.connect.data.Struct
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.slf4j.LoggerFactory
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider
import software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient
import software.amazon.awssdk.regions.Region
import software.amazon.awssdk.services.glue.GlueClient
import software.amazon.awssdk.services.glue.model.DataFormat
import software.amazon.awssdk.services.glue.model.DeleteSchemaRequest
import software.amazon.awssdk.services.glue.model.EntityNotFoundException
import software.amazon.awssdk.services.glue.model.SchemaId
import java.net.URI
import java.util.UUID

/**
 * The test class for the Protobuf Kafka Connect converter against a live Glue Schema Registry.
 */
class ProtobufSchemaConverterIntegrationTest {
    @Test
    fun fromConnectData_roundTripsStructWithoutSchemaParametersThroughGlue() {
        val childSchema =
            SchemaBuilder
                .struct()
                .name("$AUTOGENERATED_PACKAGE.Parent.Child")
                .field("value", Schema.STRING_SCHEMA)
                .build()
        val parentSchema =
            SchemaBuilder
                .struct()
                .name("Parent")
                .field("child", childSchema)
                .build()
        val parentData =
            Struct(parentSchema).put("child", Struct(childSchema).put("value", "test-value"))

        val configuration =
            mapOf(
                AWSSchemaRegistryConstants.AWS_REGION to REGION,
                AWSSchemaRegistryConstants.AWS_ENDPOINT to ENDPOINT,
                AWSSchemaRegistryConstants.REGISTRY_NAME to AWSSchemaRegistryConstants.DEFAULT_REGISTRY_NAME,
                AWSSchemaRegistryConstants.SCHEMA_NAME to SCHEMA_NAME,
                AWSSchemaRegistryConstants.DATA_FORMAT to DataFormat.PROTOBUF.name,
                AWSSchemaRegistryConstants.SCHEMA_AUTO_REGISTRATION_SETTING to true,
                AWSSchemaRegistryConstants.COMPATIBILITY_SETTING to "NONE",
            )

        val converter = ProtobufSchemaConverter()
        converter.configure(configuration, false)

        val serializedData = converter.fromConnectData(TOPIC_NAME, parentSchema, parentData)
        assertTrue(serializedData.isNotEmpty())

        val result = converter.toConnectData(TOPIC_NAME, serializedData)
        assertTrue(result.value() is Struct)
        val resultChild = (result.value() as Struct).getStruct("child")
        assertEquals("test-value", resultChild.getString("value"))
    }

    companion object {
        private val log = LoggerFactory.getLogger(ProtobufSchemaConverterIntegrationTest::class.java)

        private const val AUTOGENERATED_PACKAGE =
            "com.amazonaws.services.schemaregistry.kafkaconnect.autogenerated"

        private val REGION = GlueSchemaRegistryConnectionProperties.REGION
        private val ENDPOINT = GlueSchemaRegistryConnectionProperties.ENDPOINT
        private val SCHEMA_NAME = "gsr-protobuf-connect-null-${UUID.randomUUID()}"
        private val TOPIC_NAME = "$SCHEMA_NAME-topic"

        @AfterAll
        @JvmStatic
        fun tearDown() {
            GlueClient
                .builder()
                .credentialsProvider(DefaultCredentialsProvider.create())
                .region(Region.of(REGION))
                .endpointOverride(URI.create(ENDPOINT))
                .httpClient(UrlConnectionHttpClient.create())
                .build()
                .use { glueClient ->
                    val request =
                        DeleteSchemaRequest
                            .builder()
                            .schemaId(
                                SchemaId
                                    .builder()
                                    .registryName(AWSSchemaRegistryConstants.DEFAULT_REGISTRY_NAME)
                                    .schemaName(SCHEMA_NAME)
                                    .build(),
                            ).build()

                    try {
                        glueClient.deleteSchema(request)
                    } catch (e: EntityNotFoundException) {
                        log.info("Schema {} was never created, nothing to clean up: {}", SCHEMA_NAME, e.message)
                    }
                }
        }
    }
}
