/*
 * Copyright 2022 Amazon.com, Inc. or its affiliates.
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.amazonaws.services.schemaregistry.kafkaconnect.protobuf

import additionalTypes.Decimals
import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.CommonTestHelper.createConnectSchema
import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ConnectSchemaToProtobufSchemaConverter
import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ProtobufSchemaConverterConstants.DECIMAL_DEFAULT_SCALE
import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ProtobufSchemaConverterConstants.PROTOBUF_TAG
import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ProtobufSchemaConverterConstants.PROTOBUF_TYPE
import com.google.protobuf.ByteString
import com.google.protobuf.Descriptors
import com.google.protobuf.DynamicMessage
import org.apache.kafka.connect.data.Date
import org.apache.kafka.connect.data.Decimal
import org.apache.kafka.connect.data.Schema
import org.apache.kafka.connect.data.SchemaBuilder
import org.apache.kafka.connect.data.Struct
import org.apache.kafka.connect.data.Time
import org.apache.kafka.connect.data.Timestamp
import java.math.BigDecimal
import java.nio.ByteBuffer
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Paths

/**
 * Builds the Connect schemas and their expected protobuf counterparts. The @SneakyThrows of the
 * Java original disappear: Kotlin has no checked exceptions to swallow.
 */
object ToProtobufTestDataGenerator {
    private const val TEST_RESOURCE_PATH = "src/test/resources/"

    private fun getFullName(
        schemaName: String,
        fieldName: String,
    ): String = "com.amazonaws.services.schemaregistry.kafkaconnect.autogenerated.$schemaName.$fieldName"

    @JvmStatic
    fun getPrimitiveSchema(name: String): Schema = createConnectSchema(name, getPrimitiveTypes(), emptyMap())

    @JvmStatic
    fun getProtobufSchema(fileName: String): String = String(Files.readAllBytes(Paths.get(TEST_RESOURCE_PATH, fileName)), StandardCharsets.UTF_8)
        .replace("\r\n", "\n")

    @JvmStatic
    fun getProtobufPrimitiveMessage(): DynamicMessage {
        val fileDescriptor = getPrimitiveFileDescriptor()
        val descriptor = fileDescriptor.messageTypes[0]
        val builder = DynamicMessage.newBuilder(descriptor)
        val field = { name: String -> descriptor.findFieldByName(name) }

        return builder
            .setField(descriptor.findFieldByName("i8"), 2)
            .setField(field("i8WithParam"), 0)
            // This shouldn't be set by the converter as it's null
            // .setField(field("i8Optional"), null)
            .setField(field("i8WithDefault"), 10)
            .setField(field("i16"), 255)
            .setField(field("i16WithParam"), 234)
            .setField(field("i16WithDefault"), 15)
            .setField(field("i16Optional"), 87)
            .setField(field("i32"), 123123)
            .setField(field("i32WithParam"), 23982)
            .setField(field("i32WithSameTypeMetadata"), 2345)
            .setField(field("i32WithMetadata"), -1829)
            .setField(field("i32WithAnotherMetadata"), 123)
            .setField(field("i32WithDefault"), 0)
            // This shouldn't be set by the converter as it's null
            // .setField(field("i32Optional"), null)
            .setField(field("i64"), -23499L)
            .setField(field("i64WithParam"), 7659L)
            .setField(field("i64WithDefault"), 1238102931L)
            .setField(field("i64WithSameTypeMetadata"), 8294L)
            .setField(field("i64WithMetadata"), 9123L)
            .setField(field("i64WithAnotherMetadata"), 8272L)
            .setField(field("i64WithYetAnotherMetadata"), 80123)
            .setField(field("i64Optional"), 91010L)
            .setField(field("f32"), 34.56f)
            .setField(field("f32WithParam"), 89.00f)
            .setField(field("f32Optional"), 81232.1234566f)
            .setField(field("f32WithDefault"), 2456f)
            .setField(field("f64"), 9123.0)
            .setField(field("f64WithParam"), 91202.213)
            .setField(field("f64Optional"), -927.456)
            .setField(field("f64WithDefault"), 0.0023)
            .setField(field("bool"), true)
            .setField(field("boolWithParam"), true)
            // This shouldn't be set by the converter as it's null
            // .setField(field("boolOptional"), null)
            .setField(field("boolWithDefault"), false)
            .setField(field("bytes"), ByteString.copyFrom(byteArrayOf(1, 5, 6, 7)))
            .setField(field("bytesWithParam"), ByteString.copyFrom(byteArrayOf(1)))
            // This shouldn't be set by the converter as it's null
            // .setField(field("bytesOptional"), null)
            .setField(field("bytesWithDefault"), ByteString.copyFrom(ByteBuffer.wrap(byteArrayOf(1, 4, 5, 6))))
            .setField(field("str"), "asdsai131")
            .setField(field("strWithParam"), "12351")
            // This shouldn't be set by the converter as it's null
            // .setField(field("strOptional"), null)
            .setField(field("strWithDefault"), "")
            .build()
    }

    private fun getPrimitiveFileDescriptor(): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getPrimitiveSchema("primitiveProtobufSchema"))

    @JvmStatic
    fun getPrimitiveTypesData(): Struct {
        val connectSchema = createConnectSchema("primitiveProtobufSchema", getPrimitiveTypes(), emptyMap())
        val connectData = Struct(connectSchema)

        connectData
            .put("i8", 2.toByte())
            .put("i8WithParam", 0.toByte())
            .put("i8Optional", null)
            .put("i8WithDefault", 10.toByte())
            .put("i16", 255.toShort())
            .put("i16WithParam", 234.toShort())
            .put("i16WithDefault", 15.toShort())
            .put("i16Optional", 87.toShort())
            .put("i32", 123123)
            .put("i32WithParam", 23982)
            .put("i32WithSameTypeMetadata", 2345)
            .put("i32WithMetadata", -1829)
            .put("i32WithAnotherMetadata", 123)
            .put("i32WithDefault", 0)
            .put("i32Optional", null)
            .put("i64", -23499L)
            .put("i64WithParam", 7659L)
            .put("i64WithDefault", 1238102931L)
            .put("i64WithSameTypeMetadata", 8294L)
            .put("i64WithMetadata", 9123L)
            .put("i64WithAnotherMetadata", 8272L)
            .put("i64WithYetAnotherMetadata", 80123L)
            .put("i64Optional", 91010L)
            .put("f32", 34.56f)
            .put("f32WithParam", 89.00f)
            .put("f32Optional", 81232.1234566f)
            .put("f32WithDefault", 2456f)
            .put("f64", 9123.0)
            .put("f64WithParam", 91202.213)
            .put("f64Optional", -927.456)
            .put("f64WithDefault", 0.0023)
            .put("bool", true)
            .put("boolWithParam", true)
            .put("boolOptional", null)
            .put("boolWithDefault", false)
            .put("bytes", byteArrayOf(1, 5, 6, 7))
            .put("bytesWithParam", byteArrayOf(1))
            .put("bytesOptional", null)
            .put("bytesWithDefault", ByteBuffer.wrap(byteArrayOf(1, 4, 5, 6)))
            .put("str", "asdsai131")
            .put("strWithParam", "12351")
            .put("strOptional", null)
            .put("strWithDefault", "")
        return connectData
    }

    private fun getPrimitiveTypes(): Map<String, Schema> = linkedMapOf(
        "i8" to SchemaBuilder(Schema.Type.INT8).build(),
        "i8WithParam" to SchemaBuilder(Schema.Type.INT8).parameter(PROTOBUF_TAG, "2000").build(),
        "i8Optional" to SchemaBuilder(Schema.Type.INT8).optional().build(),
        "i8WithDefault" to SchemaBuilder(Schema.Type.INT8).defaultValue(1.toByte()).build(),
        "i16" to SchemaBuilder(Schema.Type.INT16).build(),
        "i16WithParam" to SchemaBuilder(Schema.Type.INT16).parameter(PROTOBUF_TAG, "4123").build(),
        "i16WithDefault" to SchemaBuilder(Schema.Type.INT16).defaultValue(890.toShort()).build(),
        "i16Optional" to SchemaBuilder(Schema.Type.INT16).optional().build(),
        "i32" to SchemaBuilder(Schema.Type.INT32).build(),
        "i32WithParam" to SchemaBuilder(Schema.Type.INT32).parameter(PROTOBUF_TAG, "8123").build(),
        "i32WithSameTypeMetadata" to SchemaBuilder(Schema.Type.INT32).parameter(PROTOBUF_TYPE, "INT32").build(),
        "i32WithMetadata" to SchemaBuilder(Schema.Type.INT32).parameter(PROTOBUF_TYPE, "sint32").build(),
        "i32WithAnotherMetadata" to SchemaBuilder(Schema.Type.INT32).parameter(PROTOBUF_TYPE, "sfixed32").build(),
        "i32WithDefault" to SchemaBuilder(Schema.Type.INT32).defaultValue(21233).build(),
        "i32Optional" to SchemaBuilder(Schema.Type.INT32).optional().build(),
        "i64" to SchemaBuilder(Schema.Type.INT64).build(),
        "i64WithParam" to SchemaBuilder(Schema.Type.INT64).parameter(PROTOBUF_TAG, "9123").build(),
        "i64WithDefault" to SchemaBuilder(Schema.Type.INT64).defaultValue(Long.MAX_VALUE).build(),
        "i64WithSameTypeMetadata" to SchemaBuilder(Schema.Type.INT64).parameter(PROTOBUF_TYPE, "int64").build(),
        "i64WithMetadata" to SchemaBuilder(Schema.Type.INT64).parameter(PROTOBUF_TYPE, "sint64").build(),
        "i64WithAnotherMetadata" to SchemaBuilder(Schema.Type.INT64).parameter(PROTOBUF_TYPE, "fixed64").build(),
        "i64WithYetAnotherMetadata" to SchemaBuilder(Schema.Type.INT64).parameter(PROTOBUF_TYPE, "uint32").build(),
        "i64Optional" to SchemaBuilder(Schema.Type.INT64).optional().build(),
        "f32" to SchemaBuilder(Schema.Type.FLOAT32).build(),
        "f32WithParam" to SchemaBuilder(Schema.Type.FLOAT32).parameter(PROTOBUF_TAG, "10923").build(),
        "f32Optional" to SchemaBuilder(Schema.Type.FLOAT32).optional().build(),
        "f32WithDefault" to SchemaBuilder(Schema.Type.FLOAT32).defaultValue(123.2324f).build(),
        "f64" to SchemaBuilder(Schema.Type.FLOAT64).build(),
        "f64WithParam" to SchemaBuilder(Schema.Type.FLOAT64).parameter(PROTOBUF_TAG, "1112").build(),
        "f64Optional" to SchemaBuilder(Schema.Type.FLOAT64).optional().build(),
        "f64WithDefault" to SchemaBuilder(Schema.Type.FLOAT64).defaultValue(123112322232.2644).build(),
        "bool" to SchemaBuilder(Schema.Type.BOOLEAN).build(),
        "boolWithParam" to SchemaBuilder(Schema.Type.BOOLEAN).parameter(PROTOBUF_TAG, "12123").build(),
        "boolOptional" to SchemaBuilder(Schema.Type.BOOLEAN).optional().build(),
        "boolWithDefault" to SchemaBuilder(Schema.Type.BOOLEAN).defaultValue(true).build(),
        "bytes" to SchemaBuilder(Schema.Type.BYTES).build(),
        "bytesWithParam" to SchemaBuilder(Schema.Type.BYTES).parameter(PROTOBUF_TAG, "18924").build(),
        "bytesOptional" to SchemaBuilder(Schema.Type.BYTES).optional().build(),
        "bytesWithDefault" to
            SchemaBuilder(Schema.Type.BYTES).defaultValue(byteArrayOf(3, 4, 'f'.code.toByte(), 123)).build(),
        "str" to SchemaBuilder(Schema.Type.STRING).build(),
        "strWithParam" to SchemaBuilder(Schema.Type.STRING).parameter(PROTOBUF_TAG, "13912").build(),
        "strOptional" to SchemaBuilder(Schema.Type.STRING).optional().build(),
        "strWithDefault" to SchemaBuilder(Schema.Type.STRING).defaultValue("foobarxyz").build(),
    )

    @JvmStatic
    fun getEnumSchema(schemaName: String): Schema = createConnectSchema(schemaName, getEnumType(schemaName), emptyMap())

    @JvmStatic
    fun getProtobufEnumMessage(schemaName: String): DynamicMessage {
        val fileDescriptor = getEnumFileDescriptor(schemaName)
        val descriptor = fileDescriptor.messageTypes[0]
        val builder = DynamicMessage.newBuilder(descriptor)

        return builder
            .setField(
                descriptor.findFieldByName("corpus"),
                descriptor.findEnumTypeByName("Corpus").findValueByName("UNIVERSAL"),
            ).setField(
                descriptor.findFieldByName("shapes"),
                descriptor.findEnumTypeByName("ShapesWithParam").findValueByName("TRIANGLE"),
            ).setField(
                descriptor.findFieldByName("color"),
                descriptor.findEnumTypeByName("Colors").findValueByName("BLUE"),
            ).setField(
                descriptor.findFieldByName("fruits"),
                descriptor.findEnumTypeByName("FruitsWithDefault").findValueByName("BANANA"),
            ).build()
    }

    private fun getEnumFileDescriptor(schemaName: String): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getEnumSchema(schemaName))

    @JvmStatic
    fun getEnumTypeData(schemaName: String): Struct {
        val connectSchema = createConnectSchema(schemaName, getEnumType(schemaName), emptyMap())
        val connectData = Struct(connectSchema)

        connectData
            .put("corpus", "UNIVERSAL")
            .put("shapes", "TRIANGLE")
            .put("color", "BLUE")
        // .put("fruits", "BANANA"); //Unset to check default value

        return connectData
    }

    private fun getEnumType(schemaName: String): Map<String, Schema> = linkedMapOf(
        "corpus" to
            SchemaBuilder(Schema.Type.STRING)
                .parameter("protobuf.type", "enum")
                .parameter("PROTOBUF_ENUM_VALUE.UNIVERSAL", "0")
                .parameter("PROTOBUF_ENUM_VALUE.WEB", "1")
                .parameter("PROTOBUF_ENUM_VALUE.NEWS", "4")
                .parameter("PROTOBUF_ENUM_VALUE.IMAGES", "2")
                .parameter("PROTOBUF_ENUM_VALUE.LOCAL", "3")
                .parameter("PROTOBUF_ENUM_VALUE.PRODUCTS", "5")
                .parameter("PROTOBUF_ENUM_VALUE.VIDEO", "6")
                .parameter("ENUM_NAME", getFullName(schemaName, "EnumType.Corpus"))
                .parameter("protobuf.tag", "1")
                .build(),
        "shapes" to
            SchemaBuilder(Schema.Type.STRING)
                .parameter("protobuf.type", "enum")
                .parameter("PROTOBUF_ENUM_VALUE.SQUARE", "0")
                .parameter("PROTOBUF_ENUM_VALUE.CIRCLE", "1")
                .parameter("PROTOBUF_ENUM_VALUE.TRIANGLE", "2")
                .parameter("ENUM_NAME", getFullName(schemaName, "EnumType.ShapesWithParam"))
                .parameter("protobuf.tag", "12345")
                .build(),
        "color" to
            SchemaBuilder(Schema.Type.STRING)
                .parameter("protobuf.type", "enum")
                .parameter("PROTOBUF_ENUM_VALUE.BLACK", "0")
                .parameter("PROTOBUF_ENUM_VALUE.RED", "1")
                .parameter("PROTOBUF_ENUM_VALUE.GREEN", "2")
                .parameter("PROTOBUF_ENUM_VALUE.BLUE", "3")
                .parameter("ENUM_NAME", getFullName(schemaName, "EnumType.Colors"))
                .parameter("protobuf.tag", "2")
                .optional()
                .build(),
        "fruits" to
            SchemaBuilder(Schema.Type.STRING)
                .defaultValue("BANANA")
                .parameter("protobuf.type", "enum")
                .parameter("PROTOBUF_ENUM_VALUE.APPLE", "0")
                .parameter("PROTOBUF_ENUM_VALUE.ORANGE", "1")
                .parameter("PROTOBUF_ENUM_VALUE.BANANA", "2")
                .parameter("ENUM_NAME", getFullName(schemaName, "EnumType.FruitsWithDefault"))
                .parameter("protobuf.tag", "3")
                .optional()
                .build(),
    )

    @JvmStatic
    fun getTimeSchema(name: String): Schema = createConnectSchema(name, getTimeTypes(), emptyMap())

    @JvmStatic
    fun getProtobufTimeMessage(): DynamicMessage {
        val fileDescriptor = getTimeFileDescriptor()
        val descriptor = fileDescriptor.messageTypes[0]
        val builder = DynamicMessage.newBuilder(descriptor)

        val dateBuilder = com.google.type.Date.newBuilder()
        dateBuilder.setYear(2022)
        dateBuilder.setMonth(3)
        dateBuilder.setDay(20)

        val todBuilder = com.google.type.TimeOfDay.newBuilder()
        todBuilder.setHours(2)
        todBuilder.setMinutes(2)
        todBuilder.setSeconds(42)

        val timestampBuilder = com.google.protobuf.Timestamp.newBuilder()
        timestampBuilder.setSeconds(1)
        timestampBuilder.setNanos(805000000)

        return builder
            .setField(descriptor.findFieldByName("date"), dateBuilder.build())
            .setField(descriptor.findFieldByName("time"), todBuilder.build())
            .setField(descriptor.findFieldByName("timestamp"), timestampBuilder.build())
            .build()
    }

    private fun getTimeFileDescriptor(): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getTimeSchema("timeProtobufSchema"))

    @JvmStatic
    fun getTimeTypeData(): Struct {
        val connectSchema = createConnectSchema("timeProtobufSchema", getTimeTypes(), emptyMap())
        val connectData = Struct(connectSchema)

        val dateDefVal = 19071 // equal to 2022/03/20 with reference to the unix epoch
        val timeDefVal = 7362000 // equal to 2 hours 2 minutes 42 seconds in millisecond
        val tsDefVal = 1805L // equal to 1 second 805000000 nanoseconds in millisecond
        val date = Date.toLogical(Date.SCHEMA, dateDefVal)
        val time = Time.toLogical(Time.SCHEMA, timeDefVal)
        val timestamp = Timestamp.toLogical(Timestamp.SCHEMA, tsDefVal)

        connectData
            .put("date", date)
            .put("time", time)
            .put("timestamp", timestamp)
        return connectData
    }

    private fun getTimeTypes(): Map<String, Schema> = linkedMapOf(
        "date" to Date.builder().doc("date field").build(),
        "time" to Time.builder().doc("time field").build(),
        "timestamp" to Timestamp.builder().doc("timestamp field").build(),
    )

    @JvmStatic
    fun getDecimalSchema(name: String): Schema = createConnectSchema(name, getDecimalTypes(), emptyMap())

    @JvmStatic
    fun getProtobufDecimalMessage(): DynamicMessage {
        val fileDescriptor = getDecimalFileDescriptor()
        val descriptor = fileDescriptor.messageTypes[0]
        val builder = DynamicMessage.newBuilder(descriptor)

        val decimalBuilder = Decimals.Decimal.newBuilder()
        decimalBuilder.setUnits(1234)
        decimalBuilder.setFraction(567890000)
        decimalBuilder.setPrecision(9)
        decimalBuilder.setScale(5)

        val decimalLargeScale = Decimals.Decimal.newBuilder()
        decimalLargeScale.setUnits(1234)
        decimalLargeScale.setFraction(567891340)
        decimalLargeScale.setPrecision(12)
        decimalLargeScale.setScale(8)

        val decimalZeroScale = Decimals.Decimal.newBuilder()
        decimalZeroScale.setUnits(1234)
        decimalZeroScale.setFraction(0)
        decimalZeroScale.setPrecision(4)
        decimalZeroScale.setScale(0)

        return builder
            .setField(descriptor.findFieldByName("decimal"), decimalBuilder.build())
            .setField(descriptor.findFieldByName("decimalLargeScale"), decimalLargeScale.build())
            .setField(descriptor.findFieldByName("decimalZeroScale"), decimalZeroScale.build())
            .build()
    }

    private fun getDecimalFileDescriptor(): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getDecimalSchema("decimalProtobufSchema"))

    @JvmStatic
    fun getDecimalTypeData(): Struct {
        val connectSchema = createConnectSchema("decimalProtobufSchema", getDecimalTypes(), emptyMap())
        val connectData = Struct(connectSchema)

        val decimal = BigDecimal.valueOf(1234.56789)
        val decimalLargeScale = BigDecimal.valueOf(1234.56789134)
        val decimalZeroScale = BigDecimal.valueOf(1234)

        connectData
            .put("decimal", decimal)
            .put("decimalLargeScale", decimalLargeScale)
            .put("decimalZeroScale", decimalZeroScale)
        return connectData
    }

    private fun getDecimalTypes(): Map<String, Schema> = linkedMapOf(
        "decimal" to Decimal.builder(DECIMAL_DEFAULT_SCALE),
        "decimalLargeScale" to Decimal.builder(DECIMAL_DEFAULT_SCALE).parameter("connect.decimal.scale", "10"),
        "decimalZeroScale" to Decimal.builder(DECIMAL_DEFAULT_SCALE).parameter("connect.decimal.scale", "1"),
    )

    @JvmStatic
    fun getArraySchema(name: String): Schema = createConnectSchema(name, getArrayType(), emptyMap())

    @JvmStatic
    fun getProtobufArrayMessage(): DynamicMessage {
        val fileDescriptor = getArrayFileDescriptor()
        val descriptor = fileDescriptor.messageTypes[0]
        val builder = DynamicMessage.newBuilder(descriptor)
        val field = { name: String -> descriptor.findFieldByName(name) }

        return builder
            .setField(field("str"), listOf("foo", "bar", "baz"))
            .setField(field("boolean"), listOf(true, false))
            .setField(field("i32"), ArrayList<Any>())
            .build()
    }

    private fun getArrayFileDescriptor(): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getArraySchema("arrayProtobufSchema"))

    @JvmStatic
    fun getArrayTypeData(): Struct {
        val connectSchema = createConnectSchema("arrayProtobufSchema", getArrayType(), emptyMap())
        val connectData = Struct(connectSchema)

        connectData
            .put("str", listOf("foo", "bar", "baz"))
            .put("boolean", listOf(true, false))
            .put("i32", ArrayList<Any>())
        return connectData
    }

    private fun getArrayType(): Map<String, Schema> = linkedMapOf(
        "str" to SchemaBuilder.array(Schema.STRING_SCHEMA).build(),
        "i32" to SchemaBuilder.array(Schema.INT32_SCHEMA).build(),
        "boolean" to SchemaBuilder.array(Schema.BOOLEAN_SCHEMA).build(),
    )

    @JvmStatic
    fun getMapSchema(name: String): Schema = createConnectSchema(name, getMapType(), emptyMap())

    @JvmStatic
    fun getProtobufMapMessage(): DynamicMessage {
        val fileDescriptor = getMapFileDescriptor()
        val descriptor = fileDescriptor.messageTypes[0]
        val builder = DynamicMessage.newBuilder(descriptor)

        val intMapDescriptor = descriptor.findNestedTypeByName("IntMapEntry")
        val intMapBuilder =
            DynamicMessage
                .newBuilder(intMapDescriptor)
                .setField(intMapDescriptor.findFieldByName("key"), 2)
                .setField(intMapDescriptor.findFieldByName("value"), 22)

        val boolMapDescriptor = descriptor.findNestedTypeByName("BoolMapEntry")
        val boolMapBuilder =
            DynamicMessage
                .newBuilder(boolMapDescriptor)
                .setField(boolMapDescriptor.findFieldByName("key"), "A")
                .setField(boolMapDescriptor.findFieldByName("value"), true)
        val boolMapBuilder2 =
            DynamicMessage
                .newBuilder(boolMapDescriptor)
                .setField(boolMapDescriptor.findFieldByName("key"), "B")
                .setField(boolMapDescriptor.findFieldByName("value"), false)

        return builder
            .addRepeatedField(descriptor.findFieldByName("intMap"), intMapBuilder.build())
            .addRepeatedField(descriptor.findFieldByName("boolMap"), boolMapBuilder.build())
            .addRepeatedField(descriptor.findFieldByName("boolMap"), boolMapBuilder2.build())
            .build()
    }

    private fun getMapFileDescriptor(): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getMapSchema("mapProtobufSchema"))

    @JvmStatic
    fun getMapTypeData(): Struct {
        val connectSchema = createConnectSchema("mapProtobufSchema", getMapType(), emptyMap())
        val connectData = Struct(connectSchema)

        connectData
            .put("intMap", java.util.Collections.singletonMap(2, 22))
            .put("boolMap", linkedMapOf("A" to true, "B" to false))
            .put("strMap", HashMap<Any, Any>())
        return connectData
    }

    private fun getMapType(): Map<String, Schema> = linkedMapOf(
        "intMap" to SchemaBuilder.map(Schema.INT32_SCHEMA, Schema.INT32_SCHEMA).build(),
        "boolMap" to SchemaBuilder.map(Schema.STRING_SCHEMA, Schema.BOOLEAN_SCHEMA).build(),
        "strMap" to SchemaBuilder.map(Schema.INT32_SCHEMA, Schema.STRING_SCHEMA).build(),
    )

    @JvmStatic
    fun getStructSchema(schemaName: String): Schema = createConnectSchema(schemaName, getStructType(schemaName), emptyMap())

    @JvmStatic
    fun getProtobufNestedMessage(schemaName: String): DynamicMessage {
        val fileDescriptor = getStructFileDescriptor(schemaName)
        val descriptor = fileDescriptor.messageTypes[1]
        val builder = DynamicMessage.newBuilder(descriptor)

        val addressDescriptor = fileDescriptor.messageTypes[0]
        val addressBuilder =
            DynamicMessage
                .newBuilder(addressDescriptor)
                .setField(addressDescriptor.findFieldByName("street"), "8th")
                .setField(addressDescriptor.findFieldByName("zipcode"), 98121)

        val customerDescriptor = descriptor.findNestedTypeByName("Customer")
        val customerBuilder =
            DynamicMessage
                .newBuilder(customerDescriptor)
                .setField(customerDescriptor.findFieldByName("name"), "joe")

        val mappingDescriptor = descriptor.findNestedTypeByName("MappingEntry")
        val mappingBuilder =
            DynamicMessage
                .newBuilder(mappingDescriptor)
                .setField(mappingDescriptor.findFieldByName("key"), "hello")
                .setField(mappingDescriptor.findFieldByName("value"), true)

        return builder
            .setField(descriptor.findFieldByName("address"), addressBuilder.build())
            .setField(
                descriptor.findFieldByName("status"),
                fileDescriptor.findEnumTypeByName("Status").findValueByName("VALID"),
            ).setField(descriptor.findFieldByName("customer"), customerBuilder.build())
            .setField(descriptor.findFieldByName("id"), 12365)
            .addRepeatedField(descriptor.findFieldByName("mapping"), mappingBuilder.build())
            .build()
    }

    private fun getStructFileDescriptor(schemaName: String): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getStructSchema(schemaName))

    @JvmStatic
    fun getStructTypeData(schemaName: String): Struct {
        val connectSchema = getStructSchema(schemaName)
        val connectData = Struct(connectSchema)

        connectData
            .put(
                "address",
                Struct(connectSchema.field("address").schema()).put("street", "8th").put("zipcode", 98121),
            ).put("status", "VALID")
            .put("customer", Struct(connectSchema.field("customer").schema()).put("name", "joe"))
            .put("mapping", java.util.Collections.singletonMap("hello", true))
            .put("id", 12365)
        return connectData
    }

    private fun getStructType(schemaName: String): Map<String, Schema> {
        val addressBuilder =
            SchemaBuilder
                .struct()
                .name(getFullName(schemaName, "Address"))
                .field("street", SchemaBuilder.string().parameter(PROTOBUF_TAG, "1").build())
                .field("zipcode", SchemaBuilder.int32().parameter(PROTOBUF_TAG, "2").build())
        val statusBuilder =
            SchemaBuilder(Schema.Type.STRING)
                .parameter("protobuf.type", "enum")
                .parameter("PROTOBUF_ENUM_VALUE.VALID", "0")
                .parameter("PROTOBUF_ENUM_VALUE.INVALID", "1")
                .parameter("ENUM_NAME", getFullName(schemaName, "Status"))
        val customerBuilder =
            SchemaBuilder
                .struct()
                .name(getFullName(schemaName, "NestedType.Customer"))
                .field("name", SchemaBuilder.string().parameter(PROTOBUF_TAG, "1").build())
        val mappingBuilder =
            SchemaBuilder.map(
                SchemaBuilder(Schema.Type.STRING).parameter(PROTOBUF_TAG, "1").optional().build(),
                SchemaBuilder(Schema.Type.BOOLEAN).parameter(PROTOBUF_TAG, "2").optional().build(),
            )

        return linkedMapOf(
            "address" to addressBuilder.parameter(PROTOBUF_TAG, "1").build(),
            "status" to statusBuilder.parameter(PROTOBUF_TAG, "2").build(),
            "customer" to customerBuilder.parameter(PROTOBUF_TAG, "3").build(),
            "mapping" to mappingBuilder.parameter(PROTOBUF_TAG, "4").build(),
            "id" to SchemaBuilder.int32().parameter(PROTOBUF_TAG, "5").optional().build(),
        )
    }

    @JvmStatic
    fun getOneofSchema(name: String): Schema = createConnectSchema(name, getOneofType(), emptyMap())

    @JvmStatic
    fun getProtobufOneofMessage(): DynamicMessage {
        val fileDescriptor = getOneofFileDescriptor()
        val descriptor = fileDescriptor.messageTypes[0]
        val builder = DynamicMessage.newBuilder(descriptor)
        val field = { name: String -> descriptor.findFieldByName(name) }

        return builder
            .setField(field("name"), "Jeff")
            .setField(field("shipped"), true)
            .build()
    }

    private fun getOneofFileDescriptor(): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getOneofSchema("oneofProtobufSchema"))

    @JvmStatic
    fun getOneofTypeData(): Struct {
        val connectSchema = createConnectSchema("oneofProtobufSchema", getOneofType(), emptyMap())
        val connectData = Struct(connectSchema)

        connectData
            .put("customer", Struct(connectSchema.field("customer").schema()).put("name", "Jeff"))
            .put("order", Struct(connectSchema.field("order").schema()).put("shipped", true))
        return connectData
    }

    private fun getOneofType(): Map<String, Schema> = linkedMapOf(
        "customer" to
            SchemaBuilder
                .struct()
                .name("customer")
                .field("name", SchemaBuilder.string().parameter(PROTOBUF_TAG, "5").optional().build())
                .field("age", SchemaBuilder.int32().parameter(PROTOBUF_TAG, "6").optional().build())
                .parameter("protobuf.type", "oneof")
                .optional()
                .build(),
        "order" to
            SchemaBuilder
                .struct()
                .name("order")
                .field("id", SchemaBuilder.int32().parameter(PROTOBUF_TAG, "1").optional().build())
                .field("shipped", SchemaBuilder.bool().parameter(PROTOBUF_TAG, "2").optional().build())
                .parameter("protobuf.type", "oneof")
                .optional()
                .build(),
    )

    @JvmStatic
    fun getAllTypesSchema(schemaName: String): Schema = createConnectSchema(schemaName, getAllTypes(schemaName), emptyMap())

    @JvmStatic
    fun getProtobufAllTypesMessage(schemaName: String): DynamicMessage {
        val fileDescriptor = getAllTypesFileDescriptor(schemaName)
        val descriptor = fileDescriptor.messageTypes[1]
        val builder = DynamicMessage.newBuilder(descriptor)

        val addressDescriptor = fileDescriptor.messageTypes[0]
        val addressBuilder =
            DynamicMessage
                .newBuilder(addressDescriptor)
                .setField(addressDescriptor.findFieldByName("street"), "8th")
                .setField(addressDescriptor.findFieldByName("zipcode"), 98121)

        val customerDescriptor = descriptor.findNestedTypeByName("Customer")
        val customerBuilder =
            DynamicMessage
                .newBuilder(customerDescriptor)
                .setField(customerDescriptor.findFieldByName("name"), "joe")

        val dateBuilder = com.google.type.Date.newBuilder()
        dateBuilder.setYear(2022)
        dateBuilder.setMonth(3)
        dateBuilder.setDay(20)
        val todBuilder = com.google.type.TimeOfDay.newBuilder()
        todBuilder.setHours(2)
        todBuilder.setMinutes(2)
        todBuilder.setSeconds(42)
        val timestampBuilder = com.google.protobuf.Timestamp.newBuilder()
        timestampBuilder.setSeconds(1)
        timestampBuilder.setNanos(805000000)

        val intMapDescriptor = descriptor.findNestedTypeByName("IntMapEntry")
        val intMapBuilder =
            DynamicMessage
                .newBuilder(intMapDescriptor)
                .setField(intMapDescriptor.findFieldByName("key"), 2)
                .setField(intMapDescriptor.findFieldByName("value"), 22)
        val boolMapDescriptor = descriptor.findNestedTypeByName("BoolMapEntry")
        val boolMapBuilder =
            DynamicMessage
                .newBuilder(boolMapDescriptor)
                .setField(boolMapDescriptor.findFieldByName("key"), "A")
                .setField(boolMapDescriptor.findFieldByName("value"), true)
        val boolMapBuilder2 =
            DynamicMessage
                .newBuilder(boolMapDescriptor)
                .setField(boolMapDescriptor.findFieldByName("key"), "B")
                .setField(boolMapDescriptor.findFieldByName("value"), false)

        val decimalBuilder = Decimals.Decimal.newBuilder()
        decimalBuilder.setUnits(1234)
        decimalBuilder.setFraction(567890000)
        decimalBuilder.setPrecision(9)
        decimalBuilder.setScale(5)

        val decimalWithScaleBuilder = Decimals.Decimal.newBuilder()
        decimalWithScaleBuilder.setUnits(1234)
        decimalWithScaleBuilder.setFraction(567891340)
        decimalWithScaleBuilder.setPrecision(12)
        decimalWithScaleBuilder.setScale(8)

        return builder
            .setField(descriptor.findFieldByName("i32"), 32)
            .setField(descriptor.findFieldByName("bool"), false)
            .setField(descriptor.findFieldByName("bytes"), ByteString.copyFrom(byteArrayOf(1, 5, 6, 7)))
            .setField(descriptor.findFieldByName("str"), "Hello world!")
            .setField(descriptor.findFieldByName("i8Optional"), 2)
            .setField(descriptor.findFieldByName("i16Optional"), 255)
            .setField(descriptor.findFieldByName("i64Optional"), 1080L)
            .setField(descriptor.findFieldByName("strArray"), listOf("foo", "bar", "baz"))
            .setField(descriptor.findFieldByName("boolArray"), listOf(true, false))
            .setField(descriptor.findFieldByName("intArray"), ArrayList<Any>())
            .setField(descriptor.findFieldByName("customerArray"), listOf(customerBuilder.build()))
            .setField(
                descriptor.findFieldByName("colorArray"),
                listOf(descriptor.findEnumTypeByName("Colors").findValueByName("RED")),
            ).setField(descriptor.findFieldByName("date"), dateBuilder.build())
            .setField(descriptor.findFieldByName("time"), todBuilder.build())
            .setField(descriptor.findFieldByName("timestamp"), timestampBuilder.build())
            .addRepeatedField(descriptor.findFieldByName("intMap"), intMapBuilder.build())
            .addRepeatedField(descriptor.findFieldByName("boolMap"), boolMapBuilder.build())
            .addRepeatedField(descriptor.findFieldByName("boolMap"), boolMapBuilder2.build())
            .setField(
                descriptor.findFieldByName("color"),
                descriptor.findEnumTypeByName("Colors").findValueByName("BLACK"),
            ).setField(
                descriptor.findFieldByName("progress"),
                fileDescriptor.findEnumTypeByName("Progress").findValueByName("INPROGRESS"),
            ).setField(descriptor.findFieldByName("id"), 12315)
            .setField(descriptor.findFieldByName("address"), addressBuilder.build())
            .setField(descriptor.findFieldByName("customer"), customerBuilder.build())
            .setField(descriptor.findFieldByName("decimal"), decimalBuilder.build())
            .setField(descriptor.findFieldByName("decimalWithScale"), decimalWithScaleBuilder.build())
            .build()
    }

    private fun getAllTypesFileDescriptor(schemaName: String): Descriptors.FileDescriptor = ConnectSchemaToProtobufSchemaConverter().convert(getAllTypesSchema(schemaName))

    @JvmStatic
    fun getAllTypesData(schemaName: String): Struct {
        val connectSchema = getAllTypesSchema(schemaName)
        val connectData = Struct(connectSchema)

        val dateDefVal = 19071 // equal to 2022/03/20 with reference to the unix epoch
        val timeDefVal = 7362000 // equal to 2 hours 2 minutes 42 seconds in millisecond
        val tsDefVal = 1805L // equal to 1 second 805000000 nanoseconds in millisecond
        val date = Date.toLogical(Date.SCHEMA, dateDefVal)
        val time = Time.toLogical(Time.SCHEMA, timeDefVal)
        val timestamp = Timestamp.toLogical(Timestamp.SCHEMA, tsDefVal)

        connectData
            .put("i32", 32)
            .put("bool", false)
            .put("bytes", byteArrayOf(1, 5, 6, 7))
            .put("str", "Hello world!")
            .put("i8Optional", 2.toByte())
            .put("i16Optional", 255.toShort())
            .put("i64Optional", 1080L)
            .put("strArray", listOf("foo", "bar", "baz"))
            .put("boolArray", listOf(true, false))
            .put("intArray", ArrayList<Any>())
            .put(
                "customerArray",
                listOf(Struct(connectSchema.field("customerArray").schema().valueSchema()).put("name", "joe")),
            ).put("colorArray", listOf("RED"))
            .put("date", date)
            .put("time", time)
            .put("timestamp", timestamp)
            .put("intMap", java.util.Collections.singletonMap(2, 22))
            .put("boolMap", linkedMapOf("A" to true, "B" to false))
            .put("strMap", HashMap<Any, Any>())
            .put("color", "BLACK")
            .put("progress", "INPROGRESS")
            .put("order", Struct(connectSchema.field("order").schema()).put("id", 12315))
            .put(
                "address",
                Struct(connectSchema.field("address").schema()).put("street", "8th").put("zipcode", 98121),
            ).put("customer", Struct(connectSchema.field("customer").schema()).put("name", "joe"))
            .put("decimal", BigDecimal.valueOf(1234.56789))
            .put("decimalWithScale", BigDecimal.valueOf(1234.56789134))
        return connectData
    }

    private fun getAllTypes(schemaName: String): Map<String, Schema> {
        val addressBuilder =
            SchemaBuilder
                .struct()
                .name(getFullName(schemaName, "AddressAllTypes"))
                .field("street", SchemaBuilder.string().parameter(PROTOBUF_TAG, "1").build())
                .field("zipcode", SchemaBuilder.int32().parameter(PROTOBUF_TAG, "2").build())
        val customerBuilder =
            SchemaBuilder
                .struct()
                .name(getFullName(schemaName, "AllTypes.Customer"))
                .field("name", SchemaBuilder.string().parameter(PROTOBUF_TAG, "1").build())
        val progressBuilder =
            SchemaBuilder(Schema.Type.STRING)
                .parameter("protobuf.type", "enum")
                .parameter("PROTOBUF_ENUM_VALUE.INPROGRESS", "0")
                .parameter("PROTOBUF_ENUM_VALUE.REVIEW", "1")
                .parameter("PROTOBUF_ENUM_VALUE.DONE", "2")
                .parameter("ENUM_NAME", getFullName(schemaName, "Progress"))
        val colorBuilder =
            SchemaBuilder(Schema.Type.STRING)
                .parameter("protobuf.type", "enum")
                .parameter("PROTOBUF_ENUM_VALUE.BLACK", "0")
                .parameter("PROTOBUF_ENUM_VALUE.RED", "1")
                .parameter("PROTOBUF_ENUM_VALUE.GREEN", "2")
                .parameter("PROTOBUF_ENUM_VALUE.BLUE", "3")
                .parameter("ENUM_NAME", getFullName(schemaName, "AllTypes.Colors"))
        val colorArrayBuilder =
            SchemaBuilder(Schema.Type.STRING)
                .parameter("protobuf.type", "enum")
                .parameter("PROTOBUF_ENUM_VALUE.BLACK", "0")
                .parameter("PROTOBUF_ENUM_VALUE.RED", "1")
                .parameter("PROTOBUF_ENUM_VALUE.GREEN", "2")
                .parameter("PROTOBUF_ENUM_VALUE.BLUE", "3")
                .parameter("ENUM_NAME", getFullName(schemaName, "AllTypes.Colors"))

        val intMapBuilder =
            SchemaBuilder.map(
                SchemaBuilder(Schema.Type.INT32).parameter(PROTOBUF_TAG, "1").optional().build(),
                SchemaBuilder(Schema.Type.INT32).parameter(PROTOBUF_TAG, "2").optional().build(),
            )
        val boolMapBuilder =
            SchemaBuilder.map(
                SchemaBuilder(Schema.Type.STRING).parameter(PROTOBUF_TAG, "1").optional().build(),
                SchemaBuilder(Schema.Type.BOOLEAN).parameter(PROTOBUF_TAG, "2").optional().build(),
            )
        val strMapBuilder =
            SchemaBuilder.map(
                SchemaBuilder(Schema.Type.INT32).parameter(PROTOBUF_TAG, "1").optional().build(),
                SchemaBuilder(Schema.Type.STRING).parameter(PROTOBUF_TAG, "2").optional().build(),
            )

        return linkedMapOf(
            "i32" to SchemaBuilder(Schema.Type.INT32).parameter(PROTOBUF_TAG, "1").build(),
            "bool" to SchemaBuilder(Schema.Type.BOOLEAN).parameter(PROTOBUF_TAG, "2").optional().build(),
            "bytes" to SchemaBuilder(Schema.Type.BYTES).parameter(PROTOBUF_TAG, "3").optional().build(),
            "str" to SchemaBuilder(Schema.Type.STRING).parameter(PROTOBUF_TAG, "4").optional().build(),
            "i8Optional" to SchemaBuilder(Schema.Type.INT8).parameter(PROTOBUF_TAG, "5").optional().build(),
            "i16Optional" to SchemaBuilder(Schema.Type.INT16).parameter(PROTOBUF_TAG, "6").optional().build(),
            "i64Optional" to SchemaBuilder(Schema.Type.INT64).parameter(PROTOBUF_TAG, "7").optional().build(),
            "strArray" to
                SchemaBuilder.array(Schema.STRING_SCHEMA).parameter(PROTOBUF_TAG, "8").optional().build(),
            "intArray" to
                SchemaBuilder.array(Schema.INT32_SCHEMA).parameter(PROTOBUF_TAG, "9").optional().build(),
            "boolArray" to
                SchemaBuilder.array(Schema.BOOLEAN_SCHEMA).parameter(PROTOBUF_TAG, "10").optional().build(),
            "customerArray" to
                SchemaBuilder.array(customerBuilder.build()).parameter(PROTOBUF_TAG, "25").optional().build(),
            "colorArray" to
                SchemaBuilder.array(colorArrayBuilder.build()).parameter(PROTOBUF_TAG, "26").optional().build(),
            "date" to Date.builder().parameter(PROTOBUF_TAG, "11").build(),
            "time" to Time.builder().parameter(PROTOBUF_TAG, "12").optional().build(),
            "timestamp" to Timestamp.builder().parameter(PROTOBUF_TAG, "13").optional().build(),
            "intMap" to intMapBuilder.parameter(PROTOBUF_TAG, "14").build(),
            "boolMap" to boolMapBuilder.parameter(PROTOBUF_TAG, "15").build(),
            "strMap" to strMapBuilder.parameter(PROTOBUF_TAG, "16").build(),
            "color" to colorBuilder.parameter(PROTOBUF_TAG, "17").optional().build(),
            "progress" to progressBuilder.parameter(PROTOBUF_TAG, "18").build(),
            "order" to
                SchemaBuilder
                    .struct()
                    .name("order")
                    .field("id", SchemaBuilder.int32().parameter(PROTOBUF_TAG, "19").optional().build())
                    .field("paid", SchemaBuilder.bool().parameter(PROTOBUF_TAG, "20").optional().build())
                    .parameter("protobuf.type", "oneof")
                    .optional()
                    .build(),
            "address" to addressBuilder.parameter(PROTOBUF_TAG, "21").build(),
            "customer" to customerBuilder.parameter(PROTOBUF_TAG, "22").optional().build(),
            "decimal" to
                Decimal.builder(DECIMAL_DEFAULT_SCALE).parameter(PROTOBUF_TAG, "23").optional().build(),
            "decimalWithScale" to
                Decimal
                    .builder(10)
                    .parameter(PROTOBUF_TAG, "24")
                    .parameter("connect.decimal.scale", "10")
                    .optional()
                    .build(),
        )
    }
}
