/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates.
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema

import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ProtobufSchemaConverterUtils.getSchemaSimpleName
import com.amazonaws.services.schemaregistry.kafkaconnect.protobuf.fromconnectschema.ProtobufSchemaConverterUtils.toValidFullName
import com.amazonaws.services.schemaregistry.utils.apicurio.FileDescriptorUtils
import com.google.protobuf.DescriptorProtos
import com.google.protobuf.Descriptors
import org.apache.kafka.connect.data.Schema
import org.apache.kafka.connect.errors.DataException

/**
 * Converts Kafka Connect schemas to Protobuf3 schemas.
 */
class ConnectSchemaToProtobufSchemaConverter {
    /**
     * Converts the given Kafka connect schema into a Protobuf FileDescriptor that can be used to
     * generate Protobuf objects.
     */
    fun convert(schema: Schema): Descriptors.FileDescriptor = buildFileDescriptor(buildFileDescriptorProto(schema).build())

    /**
     * Builds the file level information required for generating the Protobuf FileDescriptor.
     */
    private fun buildFileDescriptorProto(schema: Schema): DescriptorProtos.FileDescriptorProto.Builder {
        val fileDescriptorProtoBuilder = DescriptorProtos.FileDescriptorProto.newBuilder()
        val schemaName = schema.name()

        // Set to a constant value; revisit during metadata storage to make it configurable.
        fileDescriptorProtoBuilder.setPackage(PACKAGE_NAME_PREFIX + toValidFullName(schemaName))
        fileDescriptorProtoBuilder.setName("$schemaName.proto")
        // Only Proto3 syntax is supported for schema generation for now.
        fileDescriptorProtoBuilder.setSyntax(PROTO3_SYNTAX)

        // Creating the parent level struct that contains the parent level fields.
        fileDescriptorProtoBuilder.addMessageType(buildMessageDescriptorProto(schema, fileDescriptorProtoBuilder))

        return fileDescriptorProtoBuilder
    }

    private fun buildMessageDescriptorProto(
        schema: Schema,
        fileDescriptorProtoBuilder: DescriptorProtos.FileDescriptorProto.Builder,
    ): DescriptorProtos.DescriptorProto.Builder {
        val messageDescriptorProtoBuilder = DescriptorProtos.DescriptorProto.newBuilder()

        messageDescriptorProtoBuilder.setName(getSchemaSimpleName(schema.name()))

        FieldBuilder.build(schema, fileDescriptorProtoBuilder, messageDescriptorProtoBuilder)

        return messageDescriptorProtoBuilder
    }

    private fun buildFileDescriptor(
        fileDescriptorProto: DescriptorProtos.FileDescriptorProto,
    ): Descriptors.FileDescriptor = try {
        Descriptors.FileDescriptor.buildFrom(fileDescriptorProto, FileDescriptorUtils.baseDependencies())
    } catch (e: Descriptors.DescriptorValidationException) {
        throw DataException("Failed to build Protobuf FileDescriptor", e)
    }

    companion object {
        private const val PACKAGE_NAME_PREFIX =
            "com.amazonaws.services.schemaregistry.kafkaconnect.autogenerated."
        private const val PROTO3_SYNTAX = "proto3"
    }
}
